### PR TITLE
ISLANDORA-1795: Fix "invalid clip parametters passed" error if base URL path is a sub dir

### PR DESCRIPTION
**Pull request by simonhm**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1795
- Other Relevant Links: https://groups.google.com/forum/#!topic/islandora/zUjC2xvWWEc 

Clipper functionality throws an "Invalid clip parameters passed"
error if the base URL path of your site is a sub directory.

This fix will remove the sub dir (if exists) before verifying path.

### CODE REVIEW

**Comment by manez** [comment]
Hi @simonhm and thanks for the pull request! To keep our licenses in order, we ask that all code contributions be covered by a Contributor License Agreement. We'd need either an [individual CLA](http://islandora.ca/sites/default/files/islandora_cla.pdf) if this is your own work or a [Corporate CLA](http://islandora.ca/sites/default/files/islandora_ccla.pdf) if this is on behalf of your employer. You can read more about our CLAs [here](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements)

Either one can be sent ot me at manez@islandora.ca

**Comment by DiegoPino** [comment]
hi @simonhm also, please pull against the 7.x branch. The one you are pulling against, 7.x-1.7 is a release branch and is closed once the release process ends. 7.x is HEAD and MASTER and in between releases we do all the work there. I will also ping @nigelgbanks here, since he is the Maintainer to review your pull once the iCLA or CCLA is in place.

Thanks a lot and welcome to Islandora!

**Comment by manez** [comment]
iCLA now on file! Thanks @simonhm

**Comment by simonhm** [comment]
Thanks. 
And I submited new request against the 7.x branch.
https://github.com/Islandora/islandora_openseadragon/pull/67
Regards.

**Pull request closed without merging**
