### PR TITLE
Add basic viewer information and fix typos.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2112 (plus) 

# What does this Pull Request do?

Minor documentation updates.

# What's new?

Explained what this module is. Also fixed a typo in the drush command.

# How should this be tested?

Is it readable? is it accurate?

# Additional Notes:

* Does this change require documentation to be updated? The wiki has already been updated. 
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# Interested parties
@Islandora/7-x-1-x-committers and DIG co-convener @DonRichards

### CODE REVIEW

**Comment by DiegoPino** [comment]
@rosiel can you update the description of this pull please. There is an actual JIRA ticket for this https://jira.duraspace.org/browse/ISLANDORA-2112 Thanks

**Comment by rosiel** [comment]
Whoops thanks Diego! I think I asked you to make that ticket too. 😳

**Comment by rosiel** [comment]
Ping @Islandora/7-x-1-x-committers

**Review by manez — APPROVED** [review]
Looks good! Here thar be no more dradons.

**Pull request merged**
