### PR TITLE
Deprecate unused functions.

### PR DESCRIPTION
**Pull request by jonathangreen**
## JIRA Ticket

https://jira.duraspace.org/browse/ISLANDORA-2093

## What does this Pull Request do?

Adds deprecation warnings to unused functions in the solution pack.

## What's new?

Just adds deprecation warnings, so it shouldn't cause any errors.

## Additional Notes:

@adam-vessey the only usage of these functions I can find searching in GitHub is in https://github.com/discoverygarden/islandora_paged_tei_seadragon/pull/15 that was added recently. Since this function isn't used at all in the OpenSeadragon SP, maybe the function should just be pulled out and put into the TEI pack?

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by adam-vessey** [comment]
Or... should we make the relevant pieces call 'em?

Would have [similar stuff in the large image solution pack, generating the URL with the token](https://github.com/Islandora/islandora_solution_pack_large_image/blob/879902f8f632dfe3605ff3dfb856c82ba823cdfb/islandora_large_image.module#L202-L208)...

**Comment by jonathangreen** [comment]
@adam-vessey that doesn't seem like a good solution because the code you referenced is in the viewer hook code. Creating a dependancy on Openseadragon there doesn't seem desirable. 

I'd like to change the arguments that are passed to the viewer, then maybe the viewer could handle the token on its own, but changing that interface is kind of problematic at this point...

**Comment by adam-vessey** [comment]
Correct: would seem to point towards pulling out towards other shared code, like `islandora` proper, to generate a token'd URL.

**Comment by jonathangreen** [comment]
@adam-vessey are you okay with this function deprecation then?

**Comment by adam-vessey** [comment]
As things are now, no. If we get the replacing function (somewhere which makes more sense than here), yes. Without a replacement, we seem to be advocating copypasta propagation for the creation of token'd URLs anywhere they're desired/necessary.

**Comment by jonathangreen** [comment]
Bleh okay. I'll just close this then. Seems weird to leave unused functions just kicking around.

**Pull request closed without merging**
