### PR TITLE
Enable Djatoka server base URL to be configurable

### PR DESCRIPTION
**Pull request by ksclarke**
Allows the djatoka server's base url to be configurable and also performs a check to make sure what's input for this value in the admin config actually interacts with a functioning djatoka server.

### CODE REVIEW

**Comment by jonathangreen** [comment]
Hey Kevin. I really like exposing this as configuration! 

The pull appears to have failed because of some coding standards issues, can you take a look?

**Comment by ksclarke** [comment]
Oops, I ran the ant build, but apparently I didn't have the Drupal coding standards installed (and I didn't notice the warning).  I'm fixing now.

**Comment by ksclarke** [comment]
Oh, wait.  It picks up on the new commit automagically.  I didn't know that... was closing to open a new PR.

**Comment by steverweber** [comment]
Maintainer please review this for merge

**Pull request merged**
