### PR TITLE
updated link to openseadragon library

### PR DESCRIPTION
**Pull request by ppound**

### CODE REVIEW

**Comment by nhart** [comment]
i ran a quick test on openseadragon-bin-1.0.0 and it seems to work fine. tested chrome and ie9

**Comment by jordandukart** [comment]
https://jira.duraspace.org/browse/ISLANDORA-935 clipper fails in OpenSeadragon 1.0.0.

**Comment by ppound** [comment]
I can update the link to point to here https://github.com/openseadragon/openseadragon/releases and change the wording to say get the latest openseadragon release or do we want to leave the link to a version that we know works until we get a chance to test and fix any issues with the lastest release?

**Comment by jordandukart** [comment]
It breaks the clipper implementation we have on 1.0.0.

**Comment by ppound** [comment]
Can this pull request be merged it provides a link to 0.9.129 which I think has been well tested with Islandora?

**Pull request merged**
