### PR TITLE
Fixed incorrect defaults for tileOverlap setting used when creating

### PR DESCRIPTION
**Pull request by nigelgbanks**
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-2029)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

Previous conversation of issue in this pull:
https://github.com/Islandora/islandora_openseadragon/pull/65

# What does this Pull Request do?

Change the defaults used for tileOverlap, which were incorrectly set to 2 for some reason.

# What's new?

Changes the default value, as well as sorts a javascript bug when the value is set to zero, and the wrong default was being used.

# How should this be tested?

Look a some images in the openseadragon viewer and make sure that the tiles do not overlap.

# Interested parties
@DiegoPino  @giancarlobi  @willtp87

### CODE REVIEW

**Comment by DiegoPino** [comment]
@nigelgbanks 👀 https://jira.duraspace.org/browse/ISLANDORA-2029

**Review by willtp87 — APPROVED** [review]
@nigelgbanks @DiegoPino Thanks for the speed here. This returns the issue to pre update levels.

**Comment by DiegoPino** [comment]
@nigelgbanks @willtp87 will merge this and investigate further the finer grained issue as a another ticket.

**Comment by DiegoPino** [comment]
@nigelgbanks @willtp87 or, will wait 24 hrs.. what do you think?

**Comment by nigelgbanks** [comment]
@DiegoPino Good idea, I reckon the other issues @giancarlobi is having will likely take longer to sort.

**Comment by nigelgbanks** [comment]
I don't mind the lack of a wait on this one, since it's a small and obvious fix, not much to discuss.

**Comment by giancarlobi** [comment]
(Sorry if is not the right place where comment) I enabled again 2.2.1 
and last module version on V2P2.
I reset conf settings to default and changed only Maximum Zoom Level = 8 
to allow more deep zoom in.
The issue is reduced but present especially when deep zoom in.
Open this page 
http://v2p2arch.to.cnr.it/islandora/object/v2p2notext%3A166 and note 
zooming in how the zone marked by blue circle is changing.

Available for more test if needed.

**Comment by giancarlobi** [comment]
image

**Comment by whikloj** [comment]
I must have a bad monitor, because I haven't been able to see any of these issues. 
@DiegoPino just chiming in to agree with @nigelgbanks that you don't need to wait 24 hours for this. It is small and should happen.

**Comment by DiegoPino** [comment]
@nigelgbanks @whikloj @giancarlobi. I can´t see the issues after this current fix, so same as @whiklo. I mean, there are tiny issues, but the same that existed with Openseadragon 0.9 on this side. I wonder if the Javascript implementation of different Browsers + Video Card /GPU accelerators could make a difference on a newer, more "top notch" OpenSeadragon?
 This is the capture of the part that was giving Giancarlo issues using Safari and as you can see there are no stripes of tile artifacts more than normal compression dingies. I also tested on Chrome and Firefox under  OSX on a not too new Macbook pro. Wonder if, maybe, some linux/windows Graphic driver could react differently? Or maybe Javascript issues under a different Browser?

giancarlo2

**Comment by giancarlobi** [comment]
@DiegoPino you are right, I tried on different host (windows + firefox) and no issue, so this is not a code problem but my notebook with linux (both firefox and Chrome show issue).
Sorry for to be too much meticulous and thanks all for this great improvement, my next step will be test it with Cantaloupe (here http://dev.digibess.it/doku.php?id=reloaded at bottom I'll note steps).

**Comment by giancarlobi** [comment]
A last note for today (here is already tomorrow!). Enabled IIIF image server, the issue is disappeared! Next days I'll do more deep tests.

**Comment by giancarlobi** [comment]
I made more tests, also with cantaloupe, it works like a charm!
In addition I hard-coded tile-source URL replace pointing to fedora directly and also in this case was great!
A question: to add a settings to allow change tile source URL, is the best practise open a Jira ticket?
Thanks all for your great job!

**Comment by nigelgbanks** [comment]
Yup a Jira ticket seems best. 

At which point do you want to change the URL? Currently it gets passed in via the `islandora_get_viewer` function as the `jp2_url` [parameter](https://github.com/Islandora/islandora_solution_pack_large_image/blob/695e1aace43e88d5a632d91e0dc8368edb5f17e3/islandora_large_image.module#L199-L213). There is currently no alter for the `islandora_get_viewer` function so if I take your meaning correctly it might be such a feature would likely touch on several modules including Islandora.

**Comment by giancarlobi** [comment]
@nigelgbanks my idea is to be able to set "tile source URL" and possibly "YES/NO token" from admin settings, for all module using djatoka/iiif (large image, IABR, ?), the reason is to connect directly to fedora to download JP2 for better performance.
This http://archive.digibess.eu has both (large image and IABR) hardcoded to get JP2 from fedora and cantaluope as iiif server for openseadragon, if you want to take a look.
Make sense?!?!

**Comment by nigelgbanks** [comment]
Ah ic, something like this could be provided but I feel we should probably clean up the calling code (for `islandora_get_viewer`) as well, so we don't bother generating tokens we don't use. 

If your in a hurry to do this is in such a way as to not have to maintain hard-coded changes to the module, you could do it in you theme's `template.php` file.

```php
function THEME_NAME_preprocess_islandora_openseadragon_viewer(array &$variables) {
  module_load_include('inc', 'islandora_openseadragon', 'includes/utilities');
  $pid =  $variables['settings'];
  $matches = array();
  preg_match('/object\/[^\/]*\/datastream\/([^\/]*)/', $variables['settings']['options']['tileSources'][0]['identifier'], $matches);
  $dsid = isset($matches[1]) ? $matches[1] : NULL;
  $identifier = "YOUR_FEDORA_URL_WITH_EMBEDDED_{$pid}_{$dsid"; 
  $variables['settings']['options']['tileSources'] = islandora_openseadragon_identifier_tile_source($identifier);
}
```

**Comment by giancarlobi** [comment]
Great. I finalize some cantaluope configs and settings then I'll try your suggestion.
Later I'll open a Jira ticket.
Thanks!

**Comment by giancarlobi** [comment]
@nigelgbanks template.php works, I made some little change due to encoded string:
```php
function beginning_preprocess_islandora_openseadragon_viewer(array &$variables) {
  module_load_include('inc', 'islandora_openseadragon', 'includes/utilities');
  $pid =  $variables['settings']['pid'];
  $matches = array();
  preg_match('/datastream%2[fF](.*)%2[fF]view/', $variables['settings']['options']['tileSources'][0], $matches);
  $dsid = isset($matches[1]) ? $matches[1] : NULL;
  $identifier = "http://150.145.48.37:8080/fedora/objects/".$pid."/datastreams/".$dsid."/content";
  $variables['settings']['options']['tileSources'] = islandora_openseadragon_identifier_tile_source($identifier);
}
```
Many thanks !!!

**Pull request merged**
