### PR TITLE
Update and clarify README for 7.x-1.13

### PR DESCRIPTION
**Pull request by bencomp**
**JIRA Ticket**: n/a

# What does this Pull Request do?

This update does not present new information, but hopefully makes the README more accessible.

- add "Djatoka or IIIF image server" as requirement
- reorder installation options, implicitly prefer Drush
- explain what configuration is discussed here
- explain IIIF settings
- align IIIF settings with Djatoka settings
- make reverse proxy information more generic
- remove Apache example setup
- update Cantaloupe URLs
- use more informative link labels
- fix a few typos

# What's new?

Of the above listed changes, I consider these new-ish:

- add "Djatoka or IIIF image server" as requirement
- explain what configuration is discussed here
- explain IIIF settings
- align IIIF settings with Djatoka settings
- make reverse proxy information more generic
- remove Apache example setup
- update Cantaloupe URLs
- use more informative link labels

# How should this be tested?

Please read.

# Additional Notes:

I haven't touched the wiki page yet.

# Interested parties

@DiegoPino, @DonRichards and @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by manez** [comment]
@bencomp can you make a PR on the main branch as well, so this gets into future releases?

**Review by DiegoPino — APPROVED** [review]
Will wait for the 7.x equivalent pull and merge both. Nice work on the docs @bencomp !

**Comment by whikloj** [comment]
@bencomp &lt;bump&gt;

**Comment by whikloj** [comment]
@DiegoPino if you want to merge this, I can make the PR for 7.x using this commit.

**Comment by bencomp** [comment]
@whikloj I'm happy to make the commit myself, but I was out of town for a few days and have not had time yet. I can do it tonight.

**Comment by whikloj** [comment]
@bencomp if you can open the PR on 7.x that would be great. You can also mark your documentation work on this module as "Done" 🎉

**Pull request merged**
