### PR TITLE
Warn users about permissions required by open seadragon

### PR DESCRIPTION
**Pull request by nhart**
Warn users about permissions required by open seadragon. This is using the new permissions in https://github.com/Islandora/islandora/pull/231

### CODE REVIEW

**Comment by jonathangreen** [comment]
I'm not sure this is true anymore. We are passing tokens now to try to bypass this.

**Comment by nhart** [comment]
Has that change been committed anywhere? I just pulled down the latest islandora 7 and open seadragon.

**Comment by jonathangreen** [comment]
Heres the code I was thinking about:

https://github.com/Islandora/islandora_solution_pack_large_image/blob/7.x/islandora_large_image.module#L186-L194

**Comment by jonathangreen** [comment]
and here:
https://github.com/Islandora/islandora/blob/7.x/islandora.module#L165-L169

Although this might not work unless anonymous has access to view datastreams, but we should probably change it so that it does work.

**Comment by nhart** [comment]
Yeah, I have all the latest code and it's not working, if that permission isn't enabled. (there's no xacml on this object)

**Comment by jonathangreen** [comment]
Do you have any time to work on it? I think we should allow this if the user you currently are has the proper permissions. It means rewriting the access function to know about tokens. If you have some time I can show you what I'm thinking.

**Pull request closed without merging**
